# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FBC Conway
email: pastor@firstbaptistconway.com
# email: tamjap@gmail.com
phone: (417) 589-3232
street_address: 148 S Shiloh Ave
city: Conway
state: Missouri
zip_code: 65632

#Social Media
facebook_url: https://www.facebook.com/Conway-First-Baptist-Church-Conway-Mo-317006155160573/

description: >- # this means to ignore newlines until "baseurl:"
  Conway First Baptist, Conway, MO.  Serving God; Serving Others.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.firstbaptistconway.com" # the base hostname & protocol for your site, e.g. http://example.com
excerpt+separator: <!--more-->

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: massively_jekyll_theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
